### PR TITLE
chore: update to lotus 1.5.2

### PR DESCRIPTION
**Pull request by vasco-santos**
This PR updates lotus API definition in typescript to `lotus@1.5.2`.

I ran https://github.com/filecoin-shipyard/js-lotus-client-schema/tree/master/go-tsgen using https://github.com/alanshaw/go2ts/pull/2 to fix a bug from the update

### CODE REVIEW

**Review by rvagg — APPROVED** [review]
hard to be sure about any of this without knowing the gory details

any idea why it changed the spacing? was there a lint step after go2ts? because I can't see an obvious change in go2ts that would change them all like this.

**Comment by vasco-santos** [comment]
Bah, this should have been my editor, I will fix this

**Comment by vasco-santos** [comment]
Linting fixed

**Review by rvagg — APPROVED** [review]
aye, much better

**Pull request merged**
